# Generated by Django 3.2.7 on 2021-09-14 07:18

import cloudinary.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='Male', max_length=50)),
                ('profile_image', cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image')),
                ('bio', models.TextField(null=True)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
