# Generated by Django 3.2.7 on 2021-09-15 14:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1631633940/dgzqbe90lqq2fq6vhdxk.png', max_length=255, verbose_name='image'),
        ),
    ]
